import type { AppData, SectionConfig, SectionKey } from "../types/app";

export const sectionConfigs: Record<SectionKey, SectionConfig> = {
  money: {
    key: "money",
    title: "Money",
    columns: [
      { key: "label", label: "Source" },
      { key: "amount", label: "Amount", type: "currency" },
      { key: "section", label: "Section" },
      { key: "weekStart", label: "Week Start", type: "date" },
      { key: "weekEnd", label: "Week End", type: "date" },
      { key: "notes", label: "Notes" },
    ],
  },
  bills: {
    key: "bills",
    title: "Bills",
    columns: [
      { key: "name", label: "Bill" },
      { key: "category", label: "Category" },
      { key: "dueDate", label: "Due Date", type: "date" },
      { key: "amount", label: "Amount", type: "currency" },
      { key: "status", label: "Status" },
      { key: "autopay", label: "Autopay" },
      { key: "notes", label: "Notes" },
    ],
  },
  income: {
    key: "income",
    title: "Income",
    columns: [
      { key: "source", label: "Source" },
      { key: "amount", label: "Amount", type: "currency" },
      { key: "date", label: "Date", type: "date" },
      { key: "type", label: "Type" },
      { key: "notes", label: "Notes" },
    ],
  },
  transactions: {
    key: "transactions",
    title: "Transactions",
    columns: [
      { key: "description", label: "Description" },
      { key: "type", label: "Type" },
      { key: "category", label: "Category", readOnly: true },
      { key: "amount", label: "Amount", type: "currency" },
      { key: "date", label: "Date", type: "date" },
      { key: "account", label: "Account" },
      { key: "recurring", label: "Recurring" },
      { key: "notes", label: "Notes" },
    ],
  },
  debt: {
    key: "debt",
    title: "Debt",
    columns: [
      { key: "name", label: "Debt" },
      { key: "balance", label: "Balance", type: "currency" },
      { key: "minimum", label: "Minimum", type: "currency" },
      { key: "rate", label: "APR" },
      { key: "priority", label: "Priority", readOnly: true },
    ],
  },
  carPayment: {
    key: "carPayment",
    title: "Car Payment",
    columns: [
      { key: "vehicle", label: "Vehicle" },
      { key: "lender", label: "Lender" },
      { key: "originalBalance", label: "Original Balance", type: "currency" },
      { key: "remainingBalance", label: "Remaining Balance", type: "currency" },
      { key: "monthlyPayment", label: "Monthly Payment", type: "currency" },
      { key: "dueDate", label: "Due Date", type: "date" },
      { key: "apr", label: "APR" },
      { key: "status", label: "Status" },
      { key: "notes", label: "Notes" },
    ],
  },
  savings: {
    key: "savings",
    title: "Savings",
    columns: [
      { key: "name", label: "Bucket" },
      { key: "balance", label: "Balance", type: "currency" },
      { key: "protected", label: "Protected?" },
      { key: "target", label: "Target", type: "currency" },
      { key: "interestRate", label: "APY %" },
      { key: "institution", label: "Institution" },
      { key: "type", label: "Type" },
      { key: "notes", label: "Notes" },
    ],
  },
  inventory: {
    key: "inventory",
    title: "Inventory",
    columns: [
      { key: "item", label: "Item" },
      { key: "category", label: "Category", readOnly: true },
      { key: "qty", label: "Qty", type: "number" },
      { key: "minNeeded", label: "Min Needed", type: "number" },
      { key: "cost", label: "Cost", type: "currency" },
      { key: "alert", label: "Alert", readOnly: true },
      { key: "notes", label: "Notes" },
    ],
  },
  goals: {
    key: "goals",
    title: "Goals",
    columns: [
      { key: "name", label: "Goal" },
      { key: "current", label: "Current", type: "currency" },
      { key: "target", label: "Target", type: "currency" },
      { key: "deadline", label: "Deadline", type: "date" },
      { key: "category", label: "Category" },
      { key: "priority", label: "Priority" },
      { key: "status", label: "Status" },
      { key: "autoAlert", label: "Auto Alert", readOnly: true },
    ],
  },
};

export function createStarterData(): AppData {
  const data = createZeroData();
  return {
    ...data,
    sections: {
      ...data.sections,
      money: [
        row("money-cash-1", {
          label: "Chime Checking",
          amount: "$2,840.32",
          section: "cash",
          weekStart: "2026-07-12",
          weekEnd: "2026-07-18",
          notes: "Primary operating cash",
        }),
        row("money-cash-2", {
          label: "Cash App",
          amount: "$640.00",
          section: "cash",
          weekStart: "2026-07-12",
          weekEnd: "2026-07-18",
          notes: "Fast access spending",
        }),
        row("money-savings-1", {
          label: "Emergency Fund",
          amount: "$12,800.00",
          section: "savings",
          notes: "Protected savings",
        }),
        row("money-borrowed-1", {
          label: "SpotMe / MyPay",
          amount: "$450.00",
          section: "borrowed",
          notes: "Repay from next paycheck",
        }),
        row("money-credit-1", {
          label: "Credit Usage",
          amount: "$1,250.00",
          section: "credit",
          notes: "Current revolving usage",
        }),
      ],
      bills: [
        row("bill-electric", {
          name: "Electric bill",
          category: "utilities",
          dueDate: "2026-07-12",
          amount: "$186.42",
          status: "upcoming",
          autopay: "No",
          priority: "critical",
          notes: "Pay today",
        }),
        row("bill-credit-card", {
          name: "Credit card minimum",
          category: "loans",
          dueDate: "2026-07-14",
          amount: "$450.00",
          status: "upcoming",
          autopay: "No",
          priority: "high",
          notes: "Avoid interest pressure",
        }),
        row("bill-insurance", {
          name: "Car insurance",
          category: "insurance",
          dueDate: "2026-07-17",
          amount: "$214.80",
          status: "upcoming",
          autopay: "Yes",
          priority: "high",
          notes: "Autopay scheduled",
        }),
        row("bill-streaming", {
          name: "Streaming bundle",
          category: "subscriptions",
          dueDate: "2026-07-21",
          amount: "$34.99",
          status: "upcoming",
          autopay: "Yes",
          priority: "low",
          notes: "Review bundle",
        }),
      ],
      income: [
        row("income-paycheck", {
          source: "Primary paycheck",
          amount: "$1,200.00",
          date: "2026-07-12",
          type: "paycheck",
          notes: "Weekly income",
        }),
        row("income-side", {
          source: "Side income",
          amount: "$250.00",
          date: "2026-07-10",
          type: "contract",
          notes: "Variable income",
        }),
      ],
      transactions: [
        row("txn-paycheck", {
          description: "Primary paycheck",
          type: "income",
          category: "Income",
          amount: "$1,200.00",
          date: "2026-07-12",
          account: "Chime Checking",
          recurring: "Yes",
          notes: "Main deposit",
        }),
        row("txn-groceries", {
          description: "Groceries",
          type: "expense",
          category: "Groceries",
          amount: "-$72.15",
          date: "2026-07-11",
          account: "Chime Checking",
          recurring: "No",
          notes: "Weekly food run",
        }),
        row("txn-gas", {
          description: "Fuel",
          type: "expense",
          category: "Fuel",
          amount: "-$48.00",
          date: "2026-07-10",
          account: "Cash App",
          recurring: "No",
          notes: "Commute",
        }),
        row("txn-savings", {
          description: "Emergency fund transfer",
          type: "transfer",
          category: "Savings",
          amount: "-$300.00",
          date: "2026-07-09",
          account: "Chime Checking",
          recurring: "Yes",
          notes: "Protected savings",
        }),
      ],
      debt: [
        row("debt-credit-card", {
          name: "Credit card",
          balance: "$8,250.00",
          minimum: "$450.00",
          rate: "21.9%",
          priority: "High",
        }),
        row("debt-personal-loan", {
          name: "Personal loan",
          balance: "$4,900.00",
          minimum: "$180.00",
          rate: "10.3%",
          priority: "Normal",
        }),
      ],
      carPayment: [
        row("car-current", {
          vehicle: "Current vehicle",
          lender: "Auto lender",
          originalBalance: "$18,500.00",
          remainingBalance: "$10,200.00",
          monthlyPayment: "$385.00",
          dueDate: "2026-07-19",
          apr: "6.9%",
          status: "active",
          notes: "Track payoff progress",
        }),
      ],
      savings: [
        row("sav-emergency", {
          name: "Emergency Fund",
          balance: "$12,800.00",
          protected: "Yes",
          target: "$18,000.00",
          interestRate: "4.25",
          institution: "High Yield Bank",
          type: "high_yield",
          notes: "Six-month target",
        }),
        row("sav-move", {
          name: "Move Out Fund",
          balance: "$3,200.00",
          protected: "No",
          target: "$15,000.00",
          interestRate: "3.9",
          institution: "Credit Union",
          type: "money_market",
          notes: "Housing goal",
        }),
      ],
      inventory: [
        row("inv-milk", { item: "Milk", qty: "0", minNeeded: "1", cost: "$4.50", notes: "Buy next" }),
        row("inv-bread", { item: "Bread", qty: "0", minNeeded: "1", cost: "$3.25", notes: "Buy next" }),
        row("inv-eggs", { item: "Eggs", qty: "1", minNeeded: "2", cost: "$5.99", notes: "Low stock" }),
        row("inv-paper", { item: "Toilet paper", qty: "2", minNeeded: "4", cost: "$12.99", notes: "Household" }),
      ],
      goals: [
        row("goal-emergency", {
          name: "Emergency Fund",
          current: "$12,800.00",
          target: "$18,000.00",
          deadline: "2026-11-15",
          category: "emergency_fund",
          priority: "high",
          status: "active",
        }),
        row("goal-vehicle", {
          name: "Vehicle Fund",
          current: "$5,600.00",
          target: "$25,000.00",
          deadline: "2027-12-31",
          category: "car",
          priority: "medium",
          status: "active",
        }),
        row("goal-debt-free", {
          name: "Debt Free",
          current: "$5,000.00",
          target: "$18,450.00",
          deadline: "2028-07-01",
          category: "other",
          priority: "critical",
          status: "active",
        }),
      ],
    },
    paycheckPlanner: {
      paycheckAmount: "$1,200.00",
      payDate: "2026-07-12",
      weekStart: "2026-07-12",
      weekEnd: "2026-07-18",
      spotMeRepayment: "$120.00",
      myPayRepayment: "$330.00",
      locked: true,
    },
    settings: {
      ...data.settings,
      accountName: "Alex",
      profileLabel: "Command Profile",
      theme: "midnight",
      accent: "blue",
      density: "compact",
      surfaceStyle: "glass",
    },
  };
}

export function createZeroData(): AppData {
  return {
    version: 2,
    sections: {
      money: [],
      bills: [],
      income: [],
      transactions: [],
      debt: [],
      carPayment: [],
      savings: [],
      inventory: [],
      goals: [],
    },
    sortBy: {},
    paycheckPlanner: {
      paycheckAmount: "",
      payDate: "",
      weekStart: "",
      weekEnd: "",
      spotMeRepayment: "",
      myPayRepayment: "",
      locked: false,
    },
    paycheckHistory: [],
    settings: {
      theme: "dark",
      accent: "blue",
      density: "compact",
      accountName: "",
      profileLabel: "Local Profile",
      localMode: true,
      notificationsEnabled: true,
      confirmBeforeReset: true,
      widgetOrder: ["total-cash", "money-snapshot", "protected-savings", "command", "balance", "bills", "inventory", "analytics", "activity", "progress", "objectives"],
      hiddenWidgets: [],
      surfaceStyle: "glass",
      sidebarCollapsed: false,
      wallpaper: "default",
      customWallpaper: "",
      backgroundOpacity: 88,
      cardOpacity: 84,
    },
  };
}

function row(id: string, cells: Record<string, string>) {
  return { id, cells };
}
